config/routes.rb
Comptassoce::Application.routes.draw do
  
	resources :compte_bancaires do
		resources :journals
		resources :journal_banques
		resources :journal_has
		resources :journal_ventes
		resources :journal_ods
	end
        resources :facture_emises, :type => "Client"
        resources :facture_recues, :type => "Fournisseur"
        resources :clients, :controller => "tiers", :type => "Client"
        resources :fournisseurs, :controller => "tiers", :type => "Fournisseur"
        resources :categorie_analytiques
        resources :categorie_comptables

  get "home/index"

  root :to => 'home#index'

end

app/models/client.rb
class Client < Tier
  has_many :facture_emise
end

app/models/compte_bancaire.rb
class CompteBancaire < ActiveRecord::Base
	has_many :journals
	has_many :journal_has
	has_many :journal_ventes
	has_many :journal_ods
	has_many :journal_banques
	belongs_to :categorie_comptable, :dependent => :destroy
end

app/models/entree_banque.rb
class EntreeBanque < EntreeJournal
  belongs_to :journal_banque
end

app/models/entree_diverse.rb
class EntreeDiverse < EntreeJournal
  belongs_to :journal_od
end

app/models/entree_journal.rb
class EntreeJournal < ActiveRecord::Base
  belongs_to :entree_journal
  belongs_to :categorie_analytique
  belongs_to :categorie_comptable
  has_one :entree_journal
end

app/models/facture.rb
class Facture < ActiveRecord::Base
	belongs_to :categorie_comptable
	belongs_to :categorie_analytique
        belongs_to :tier
end

app/models/facture_emise.rb
class FactureEmise < Facture
	has_many :entree_facture_clients
	belongs_to :client
end

app/models/facture_recue.rb
class FactureRecue < Facture
	has_many :entree_facture_fournisseurs
	belongs_to :fournisseur
end

app/models/fournisseur.rb
class Fournisseur < Tier
  has_many :facture_recue
end

app/models/journal.rb
class Journal < ActiveRecord::Base
  belongs_to :compte_bancaire
end

app/models/journal_banque.rb
class JournalBanque < Journal
  has_many :entree_banques
end

app/models/journal_ha.rb
class JournalHa < Journal
  has_many :entree_facture_fournisseurs
end

app/models/journal_od.rb
class JournalOd < Journal
	has_many :entree_diverses
end

app/models/journal_vente.rb
class JournalVente < Journal
  has_many :entree_facture_clients
end

app/models/tier.rb
class Tier < ActiveRecord::Base
      belongs_to :categorie_comptable, :dependent => :destroy
end

app/controllers/compte_bancaires_controller.rb
class CompteBancairesController < ApplicationController

before_filter :sous_classes, :only => [:new, :edit]

  #permet de recupérer les sous classes associées aux comptes bancaires
  def sous_classes
    @sous_classes = CategorieComptable.find_by_numero(5).categorie_comptables
  end
   
  # GET /compte_bancaires
  # GET /compte_bancaires.json
  def index
    @compte_bancaires = CompteBancaire.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json :@compte_bancaires }
    end
  end

  # GET /compte_bancaires/1
  # GET /compte_bancaires/1.json
  def show
    @compte_bancaire = CompteBancaire.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json :@compte_bancaire }
    end
  end

  # GET /compte_bancaires/new
  # GET /compte_bancaires/new.json
  def new
    @compte_bancaire = CompteBancaire.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json :@compte_bancaire }
    end
  end

  # GET /compte_bancaires/1/edit
  def edit
    @compte_bancaire = CompteBancaire.find(params[:id])
  end

  # POST /compte_bancaires
  # POST /compte_bancaires.json
  def create
    @compte_bancaire = CompteBancaire.new(params[:compte_bancaire])

    respond_to do |format|
      if @compte_bancaire.save
        format.html { redirect_to @compte_bancaire, :notice => 'Compte bancaire was successfully created.' }
        format.json { render json :@compte_bancaire, :status => created, :location => :@compte_bancaire }
      else
        format.html { render action :"new" }
        format.json { render json :@compte_bancaire.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /compte_bancaires/1
  # PUT /compte_bancaires/1.json
  def update
    @compte_bancaire = CompteBancaire.find(params[:id])

    respond_to do |format|
      if @compte_bancaire.update_attributes(params[:compte_bancaire])
        format.html { redirect_to @compte_bancaire, :notice => :'Compte bancaire was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action :"edit" }
        format.json { render json :@compte_bancaire.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /compte_bancaires/1
  # DELETE /compte_bancaires/1.json
  def destroy
    @compte_bancaire = CompteBancaire.find(params[:id])
    @compte_bancaire.destroy

    respond_to do |format|
      format.html { redirect_to compte_bancaires_url }
      format.json { head :ok }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/compte_bancaires_helper.rb
module CompteBancairesHelper
end

app/helpers/factures_helper.rb
module FacturesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/journal_has_helper.rb
module JournalHasHelper
end

app/helpers/journals_helper.rb
module JournalsHelper
end

app/helpers/tiers_helper.rb
module TiersHelper
end

app/views/compte_bancaires/_form.html.erb
<%= form_for(@compte_bancaire) do |f| %>
  <% if @compte_bancaire.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@compte_bancaire.errors.count, "error") %> prohibited this compte_bancaire from being saved:</h2>

      <ul>
      <% @compte_bancaire.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :banque %><br />
    <%= f.text_field :banque %>
  </div>
  <div class="field">
    <%= f.label :nom %><br />
    <%= f.text_field :nom %>
  </div>
  <div class="field">
    <%= f.label :iban %><br />
    <%= f.text_field :iban %>
  </div>
  <div class="field">
    <%= f.label :bic %><br />
    <%= f.text_field :bic %>
  </div>
  <div class="field">
    <%= f.label :proprietaire %><br />
    <%= f.text_field :proprietaire %>
  </div>
  <div class="field">
    <%= f.label :categorie_comptable %><br />
    <%= f.grouped_collection_select(:categorie_comptable_id, @sous_classes, :categorie_comptables, :numero_nom, :id, :numero_nom) %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/compte_bancaires/edit.html.erb
<h1>Edition d'un compte bancaire</h1>

<%= render 'form' %>

<%= link_to "Voir", @compte_bancaire %> |
<%= link_to "Retour", compte_bancaires_path %>

app/views/compte_bancaires/index.html.erb
<h1>Liste des comptes bancaires</h1>

<table>
  <tr>
    <th>Banque</th>
    <th>Nom</th>
    <th>Iban</th>
    <th>Bic</th>
    <th>Propriétaire</th>
    <th>Categorie Comptable</th>
    <th>Voir</th>
    <th>Editer</th>
    <th>Supprimer</th>
  </tr>

<% @compte_bancaires.each do |compte_bancaire| %>
  <tr>
    <td><%= compte_bancaire.banque %></td>
    <td><%= link_to compte_bancaire.nom, compte_bancaire_journals_path(compte_bancaire) %></td>
    <td><%= compte_bancaire.iban %></td>
    <td><%= compte_bancaire.bic %></td>
    <td><%= compte_bancaire.proprietaire %></td>
    <td><%= compte_bancaire.categorie_comptable.numero_nom %></td>
    <td><%= link_to image_tag("icons/document.png"), compte_bancaire %></td>
    <td><%= link_to image_tag("icons/write.png"), edit_compte_bancaire_path(compte_bancaire) %></td>
    <td><%= link_to image_tag("icons/delete.png"), compte_bancaire, :confirm => 'Es-tu sûr ?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to image_tag("icons/add.png"), new_compte_bancaire_path %>

app/views/compte_bancaires/new.html.erb
<h1>Creation d'un compte bancaire</h1>

<%= render 'form' %>

<%= link_to 'Back', compte_bancaires_path %>

app/views/compte_bancaires/show.html.erb
<h1>Detail du compte bancaire</h1>

<p id="notice"><%= notice %></p>

<p>
  <b>Banque:</b>
  <%= @compte_bancaire.banque %>
</p>

<p>
  <b>Nom:</b>
  <%= @compte_bancaire.nom %>
</p>

<p>
  <b>Iban:</b>
  <%= @compte_bancaire.iban %>
</p>

<p>
  <b>Bic:</b>
  <%= @compte_bancaire.bic %>
</p>

<p>
  <b>Proprietaire:</b>
  <%= @compte_bancaire.proprietaire %>
</p>

<p>
  <b>Categorie comptable:</b>
  <%= link_to @compte_bancaire.categorie_comptable.numero_nom, @compte_bancaire.categorie_comptable %>
</p>

<%= link_to 'Edit', edit_compte_bancaire_path(@compte_bancaire) %> |
<%= link_to 'Back', compte_bancaires_path %>