config/routes.rb
Comptassoce::Application.routes.draw do
  
	resources :compte_bancaires do
		resources :journals
		resources :journal_banques
		resources :journal_has
		resources :journal_ventes
		resources :journal_ods
	end
        resources :facture_emises, :type => "Client"
        resources :facture_recues, :type => "Fournisseur"
        resources :clients, :controller => "tiers", :type => "Client"
        resources :fournisseurs, :controller => "tiers", :type => "Fournisseur"
        resources :categorie_analytiques
        resources :categorie_comptables

  get "home/index"

  root :to => 'home#index'

end

app/models/client.rb
class Client < Tier
  has_many :facture_emise
end

app/models/compte_bancaire.rb
class CompteBancaire < ActiveRecord::Base
	has_many :journals
	has_many :journal_has
	has_many :journal_ventes
	has_many :journal_ods
	has_many :journal_banques
	belongs_to :categorie_comptable, :dependent => :destroy
end

app/models/entree_banque.rb
class EntreeBanque < EntreeJournal
  belongs_to :journal_banque
end

app/models/entree_diverse.rb
class EntreeDiverse < EntreeJournal
  belongs_to :journal_od
end

app/models/entree_journal.rb
class EntreeJournal < ActiveRecord::Base
  belongs_to :entree_journal
  belongs_to :categorie_analytique
  belongs_to :categorie_comptable
  has_one :entree_journal
end

app/models/facture.rb
class Facture < ActiveRecord::Base
	belongs_to :categorie_comptable
	belongs_to :categorie_analytique
        belongs_to :tier
end

app/models/facture_emise.rb
class FactureEmise < Facture
	has_many :entree_facture_clients
	belongs_to :client
end

app/models/facture_recue.rb
class FactureRecue < Facture
	has_many :entree_facture_fournisseurs
	belongs_to :fournisseur
end

app/models/fournisseur.rb
class Fournisseur < Tier
  has_many :facture_recue
end

app/models/journal.rb
class Journal < ActiveRecord::Base
  belongs_to :compte_bancaire
end

app/models/journal_banque.rb
class JournalBanque < Journal
  has_many :entree_banques
end

app/models/journal_ha.rb
class JournalHa < Journal
  has_many :entree_facture_fournisseurs
end

app/models/journal_od.rb
class JournalOd < Journal
	has_many :entree_diverses
end

app/models/journal_vente.rb
class JournalVente < Journal
  has_many :entree_facture_clients
end

app/models/tier.rb
class Tier < ActiveRecord::Base
      belongs_to :categorie_comptable, :dependent => :destroy
end

app/controllers/categorie_comptables_controller.rb
class CategorieComptablesController < ApplicationController
  # GET /categorie_comptables
  # GET /categorie_comptables.json
  def index
    @classes = CategorieComptable.where(:niveau => 1)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @categorie_comptables }
    end
  end

  # GET /categorie_comptables/1
  # GET /categorie_comptables/1.json
  def show
    @categorie_comptable = CategorieComptable.find(params[:id])
    @parents = @categorie_comptable.parents

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @categorie_comptable }
    end
  end

  # GET /categorie_comptables/new
  # GET /categorie_comptables/new.json
  def new
    @categorie_comptable = CategorieComptable.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @categorie_comptable }
    end
  end

  # GET /categorie_comptables/1/edit
  def edit
    @categorie_comptable = CategorieComptable.find(params[:id])
  end

  # POST /categorie_comptables
  # POST /categorie_comptables.json
  def create
    @categorie_comptable = CategorieComptable.new(params[:categorie_comptable])
    @categorie_comptable.classer

    respond_to do |format|
      if @categorie_comptable.save
        format.html { redirect_to @categorie_comptable, notice: 'Categorie comptable was successfully created.' }
        format.json { render json: @categorie_comptable, status: :created, location: @categorie_comptable }
      else
        format.html { render action: "new" }
        format.json { render json: @categorie_comptable.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /categorie_comptables/1
  # PUT /categorie_comptables/1.json
  def update
    @categorie_comptable = CategorieComptable.find(params[:id])

    respond_to do |format|
      if @categorie_comptable.update_attributes(params[:categorie_comptable])
        format.html { redirect_to @categorie_comptable, notice: 'Categorie comptable was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @categorie_comptable.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categorie_comptables/1
  # DELETE /categorie_comptables/1.json
  def destroy
    @categorie_comptable = CategorieComptable.find(params[:id])
    @categorie_comptable.destroy

    respond_to do |format|
      format.html { redirect_to categorie_comptables_url }
      format.json { head :ok }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categorie_comptables_helper.rb
module CategorieComptablesHelper
end

app/helpers/factures_helper.rb
module FacturesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/journals_helper.rb
module JournalsHelper
end

app/helpers/tiers_helper.rb
module TiersHelper
end

app/views/categorie_comptables/_form.html.erb
<%= form_for(@categorie_comptable) do |f| %>
  <% if @categorie_comptable.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@categorie_comptable.errors.count, "error") %> prohibited this categorie_comptable from being saved:</h2>

      <ul>
      <% @categorie_comptable.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :numero %><br />
    <%= f.text_field :numero %>
  </div>
  <div class="field">
    <%= f.label :nom %><br />
    <%= f.text_field :nom %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/categorie_comptables/edit.html.erb
<h1>Edition d'une categorie comptable</h1>

<%= render 'form' %>

<%= link_to 'Show', @categorie_comptable %> |
<%= link_to 'Back', categorie_comptables_path %>

app/views/categorie_comptables/index.html.erb
<h1>Liste des categories comptables</h1>

<% @classes.order("numero ASC").each do |classe| %>

<table>
  <caption>Classe <%= classe.numero.to_s + " : " + classe.nom %></caption>
  <tr>
    <th>Numero</th>
    <th>Nom</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% classe.categorie_comptables.order("numero ASC").each do |sous_classe| %>
  <tr>
    <th><%= sous_classe.numero %></th>
    <th><%= sous_classe.nom %></th>
    <th><%= link_to 'Show', sous_classe %></th>
    <th><%= link_to 'Edit', edit_categorie_comptable_path(sous_classe) %></th>
    <th><%= link_to 'Destroy', sous_classe, confirm: 'Are you sure?', method: :delete %></th>
  </tr>

    <% sous_classe.categorie_comptables.order("numero ASC").each do |categorie_comptable| %>
      <tr>
        <td><%= categorie_comptable.numero %></td>
        <td><%= categorie_comptable.nom %></td>
        <td><%= link_to 'Show', categorie_comptable %></td>
        <td><%= link_to 'Edit', edit_categorie_comptable_path(categorie_comptable) %></td>
        <td><%= link_to 'Destroy', categorie_comptable, confirm: 'Are you sure?', method: :delete %></td>
      </tr>
    <%end%>

  <%end%>

</table>
<br />

<%end%>


<%= link_to 'New Categorie comptable', new_categorie_comptable_path %>

app/views/categorie_comptables/new.html.erb
<h1>Creation d'une categorie comptable</h1>

<%= render 'form' %>

<%= link_to 'Back', categorie_comptables_path %>

app/views/categorie_comptables/show.html.erb
<h1>Detail de la categorie comptable</h1>

<p id="notice"><%= notice %></p>

<table>
<tr><th></th><th>Numero</th><th>Nom</th></tr>
<% libelle = "Classe" %>
<% while @parents.length > 0 %>
  <%parent = @parents.pop%>
  <tr><td><%= libelle %></td><td><%= parent.numero %></td><td><%= parent.nom %></td></tr>
  <%libelle = "Sous-" + libelle.downcase %>
<%end%> 
<tr><td><%= @categorie_comptable.libelle %></td><td><%= @categorie_comptable.numero %></td><td><%= @categorie_comptable.nom %></td></tr>


<%= link_to 'Edit', edit_categorie_comptable_path(@categorie_comptable) %> |
<%= link_to 'Back', categorie_comptables_path %>