config/routes.rb
Comptassoce::Application.routes.draw do
  
	resources :compte_bancaires do
		resources :journals
		resources :journal_banques
		resources :journal_has
		resources :journal_ventes
		resources :journal_ods
	end
        resources :facture_emises, :type => "Client"
        resources :facture_recues, :type => "Fournisseur"
        resources :clients, :controller => "tiers", :type => "Client"
        resources :fournisseurs, :controller => "tiers", :type => "Fournisseur"
        resources :categorie_analytiques
        resources :categorie_comptables

  get "home/index"

  root :to => 'home#index'

end

app/models/client.rb
class Client < Tier
  has_many :facture_emise
end

app/models/compte_bancaire.rb
class CompteBancaire < ActiveRecord::Base
	has_many :journals
	has_many :journal_has
	has_many :journal_ventes
	has_many :journal_ods
	has_many :journal_banques
	belongs_to :categorie_comptable, :dependent => :destroy
end

app/models/entree_banque.rb
class EntreeBanque < EntreeJournal
  belongs_to :journal_banque
end

app/models/entree_diverse.rb
class EntreeDiverse < EntreeJournal
  belongs_to :journal_od
end

app/models/entree_journal.rb
class EntreeJournal < ActiveRecord::Base
  belongs_to :entree_journal
  belongs_to :categorie_analytique
  belongs_to :categorie_comptable
  has_one :entree_journal
end

app/models/facture.rb
class Facture < ActiveRecord::Base
	belongs_to :categorie_comptable
	belongs_to :categorie_analytique
        belongs_to :tier
end

app/models/facture_emise.rb
class FactureEmise < Facture
	has_many :entree_facture_clients
	belongs_to :client
end

app/models/facture_recue.rb
class FactureRecue < Facture
	has_many :entree_facture_fournisseurs
	belongs_to :fournisseur
end

app/models/fournisseur.rb
class Fournisseur < Tier
  has_many :facture_recue
end

app/models/journal.rb
class Journal < ActiveRecord::Base
  belongs_to :compte_bancaire
end

app/models/journal_banque.rb
class JournalBanque < Journal
  has_many :entree_banques
end

app/models/journal_ha.rb
class JournalHa < Journal
  has_many :entree_facture_fournisseurs
end

app/models/journal_od.rb
class JournalOd < Journal
	has_many :entree_diverses
end

app/models/journal_vente.rb
class JournalVente < Journal
  has_many :entree_facture_clients
end

app/models/tier.rb
class Tier < ActiveRecord::Base
      belongs_to :categorie_comptable, :dependent => :destroy
end

app/controllers/journals_controller.rb
class JournalsController < ApplicationController

before_filter :search_compte_bancaire
  # GET /journals
  # GET /journals.json
	
	def search_compte_bancaire
		@compte_bancaire = CompteBancaire.find(params[:compte_bancaire_id])
	end
	
  def index
    @journals = @compte_bancaire.journals
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json :@journals }
    end
  end

  # GET /journals/1
  # GET /journals/1.json
  def show
    @journal = Journal.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json :@journal }
    end
  end

  # GET /journals/new
  # GET /journals/new.json
  def new
    @journal = Journal.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json :@journal }
    end
  end

  # GET /journals/1/edit
  def edit
    @journal = @compte_bancaire.journals.find(params[:id])
  end

  # POST /journals
  # POST /journals.json
  def create
		case params[:journal][:type]
			when "HA"
				@journal = @compte_bancaire.journal_has.new(params[:journal])
				
			when "VENTE"
				@journal = @compte_bancaire.journal_ventes.new(params[:journal])
				
			when "BANQUE"
				@journal = @compte_bancaire.journal_banques.new(params[:journal])
				
			when "OD"
				@journal = @compte_bancaire.journal_ods.new(params[:journal])
				
			else
				@journal = @compte_bancaire.journals.new(params[:journal])

		end
		
    respond_to do |format|
      if @journal.save
        format.html { redirect_to compte_bancaire_journals_path(@compte_bancaire), :notice => 'Le Journal a bien été ajouté !' }
        format.json { render json compte_bancaire_journals_path(@compte_bancaire), :status => created, :location => :@journal }
      else
        format.html { render :action => "new" }
        format.json { render json :@journal.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /journals/1
  # PUT /journals/1.json
  def update
    @journal = @compte_bancaire.journals.find(params[:id])

    respond_to do |format|
      if @journal.update_attributes(params[:journal])
        format.html { redirect_to compte_bancaire_journals_path(@compte_bancaire), :notice => 'Le Journal a bien été modifié !' }
        format.json { head :ok }
      else
        format.html { render :action => "edit" }
        format.json { render json :@journal.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /journals/1
  # DELETE /journals/1.json
  def destroy
		@compte_bancaire = CompteBancaire.find(params[:compte_bancaire_id])
    @journal = @compte_bancaire.journals.find(params[:id])
    @journal.destroy

    respond_to do |format|
      format.html { redirect_to compte_bancaire_journals_path(@compte_bancaire) }
      format.json { head :ok }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/factures_helper.rb
module FacturesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/journal_has_helper.rb
module JournalHasHelper
end

app/helpers/journal_ods_helper.rb
module JournalOdsHelper
end

app/helpers/journals_helper.rb
module JournalsHelper
end

app/helpers/tiers_helper.rb
module TiersHelper
end

app/views/journals/_form.html.erb
<%= form_for [@compte_bancaire,@journal], :as => :journal do |f| %>
  <% if @journal.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@journal.errors.count, "error") %> prohibited this journal from being saved:</h2>

      <ul>
      <% @journal.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
    <div class="field">
    <%= f.label :nom %><br />
    <%= f.text_field :nom %>
  </div>

  <div class="select">
	<%= f.label :type %><br/>
	<%= f.select(:type, [["HA","HA"],["VENTE","VENTE"],["BANQUE","BANQUE"],["OD","OD"]]) %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/journals/edit.html.erb
<h1>Edition d'un journal</h1>

<%= render 'form' %>

<%= link_to 'Retour', compte_bancaire_journals_path(@compte_bancaire) %>

app/views/journals/index.html.erb
<h1>Liste des journaux du compte <em><%= @compte_bancaire.nom %></em></h1>

<table>
  <tr>
	<th>Nom</th>
	<th>Type</th>
  </tr>

<% @journals.each do |journal| %>
  <tr>
	<td><%= journal.nom %></td>
	<td><%= journal.type %></td>
	<td><%= link_to image_tag("icons/write.png"), edit_compte_bancaire_journal_path(@compte_bancaire,journal) %></td>
    <td><%= link_to image_tag("icons/delete.png"), [@compte_bancaire,journal], :confirm => "Are you sure?", :method => :delete %></td>
    
  </tr>
<% end %>
</table>

<br />

<%= link_to 'Nouveau journal', new_compte_bancaire_journal_path %>

app/views/journals/new.html.erb
<h1>Nouveau Journal</h1>

<%= render 'form' %>

<%= link_to 'Retour', compte_bancaire_journals_path(@compte_bancaire) %>

app/views/journals/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_journal_path(@journal) %> |
<%= link_to 'Back', journals_path %>