config/routes.rb
Comptassoce::Application.routes.draw do
  
	resources :compte_bancaires do
		resources :journals
		resources :journal_banques
		resources :journal_has
		resources :journal_ventes
		resources :journal_ods
	end
        resources :facture_emises, :type => "Client"
        resources :facture_recues, :type => "Fournisseur"
        resources :clients, :controller => "tiers", :type => "Client"
        resources :fournisseurs, :controller => "tiers", :type => "Fournisseur"
        resources :categorie_analytiques
        resources :categorie_comptables

  get "home/index"

  root :to => 'home#index'

end

app/models/client.rb
class Client < Tier
  has_many :facture_emise
end

app/models/compte_bancaire.rb
class CompteBancaire < ActiveRecord::Base
	has_many :journals
	has_many :journal_has
	has_many :journal_ventes
	has_many :journal_ods
	has_many :journal_banques
	belongs_to :categorie_comptable, :dependent => :destroy
end

app/models/entree_banque.rb
class EntreeBanque < EntreeJournal
  belongs_to :journal_banque
end

app/models/entree_diverse.rb
class EntreeDiverse < EntreeJournal
  belongs_to :journal_od
end

app/models/entree_journal.rb
class EntreeJournal < ActiveRecord::Base
  belongs_to :entree_journal
  belongs_to :categorie_analytique
  belongs_to :categorie_comptable
  has_one :entree_journal
end

app/models/facture.rb
class Facture < ActiveRecord::Base
	belongs_to :categorie_comptable
	belongs_to :categorie_analytique
        belongs_to :tier
end

app/models/facture_emise.rb
class FactureEmise < Facture
	has_many :entree_facture_clients
	belongs_to :client
end

app/models/facture_recue.rb
class FactureRecue < Facture
	has_many :entree_facture_fournisseurs
	belongs_to :fournisseur
end

app/models/fournisseur.rb
class Fournisseur < Tier
  has_many :facture_recue
end

app/models/journal.rb
class Journal < ActiveRecord::Base
  belongs_to :compte_bancaire
end

app/models/journal_banque.rb
class JournalBanque < Journal
  has_many :entree_banques
end

app/models/journal_ha.rb
class JournalHa < Journal
  has_many :entree_facture_fournisseurs
end

app/models/journal_od.rb
class JournalOd < Journal
	has_many :entree_diverses
end

app/models/journal_vente.rb
class JournalVente < Journal
  has_many :entree_facture_clients
end

app/models/tier.rb
class Tier < ActiveRecord::Base
      belongs_to :categorie_comptable, :dependent => :destroy
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/factures_helper.rb
module FacturesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/journals_helper.rb
module JournalsHelper
end

app/helpers/tiers_helper.rb
module TiersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Comptassoce</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<table><tr><th><%= link_to "Accueil", root_path%></th><th><%= link_to "Liste des Comptes Bancaires", compte_bancaires_path%></th>
<th><%= link_to "Factures fournisseur", facture_recues_path%></th>
<th><%= link_to "Factures client", facture_emises_path%></th>
<th><%= link_to "Fournisseurs", fournisseurs_path%></th>
<th><%= link_to "Clients", clients_path%></th>
<th><%= link_to "Categories Analytiques", categorie_analytiques_path%></th>
<th><%= link_to "Categories Comptables", categorie_comptables_path%></th>
</tr></table>
<p class="notice"><%= notice %></p>
<%= yield %>

</body>
</html>